---
name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  distros:
    name: "Ubuntu with Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "pypy3"]
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Install apt dependencies
        run: |
          set -ex
          sudo apt update
          sudo apt install -y ldap-utils slapd enchant-2 libldap2-dev libsasl2-dev apparmor-utils
      - name: Disable AppArmor
        run: sudo aa-disable /usr/sbin/slapd
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Python dependencies"
        run: |
          set -xe
          python -V
          python -m pip install --upgrade pip setuptools build
          python -m pip install --upgrade tox tox-gh-actions
      - name: "build python-ldap ${{ matrix.python-version }}"
        run: "python -m build"
